# <!DOCTYPE html> <html lang="en"> <head>   <meta charset="UTF-8" />   <meta name="viewport" content="width=device-width, initial-scale=1.0" />   <title>Celebrity Social Services</title>   <style>     body {       margin: 0;       font-family: Arial, sans-serif;       background: #111;       color: white;       text-align: center;     }     header {       padding: 2rem;       background: #000;     }     header img {       height: 100px;     }     h1 {       margin-top: 1rem;       font-size: 2.5rem;     }     .tagline {       font-size: 1.25rem;       margin-top: 0.5rem;       color: #ccc;     }     .mockup {       margin: 2rem 0;     }     .mockup img {       width: 90%;       max-width: 800px;       border-radius: 10px;     }     .mission {       background: #222;       padding: 2rem 1rem;     }     .mission h2 {       font-size: >This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
